on:
  push:
    branches:
      - master
name: 🚀 Build and Deploy to Production Server
permissions:
  contents: write
jobs:
  setup:
    name: 🚧 Build
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd myfinancials
            rm -r api
            git clone https://github.com/menezedouglas/myfinancials.api.git api
            cd api
            composer install
            cp .env.example .env
            php artisan key:generate
            php artisan jwt:secret
            php artisan env:set APP_ENV=production
            php artisan env:set APP_DEBUG=false
            php artisan env:set APP_URL="${{ secrets.APP_URL }}"
            php artisan env:set DB_HOST="${{ secrets.DB_HOST }}"
            php artisan env:set DB_PORT="${{ secrets.DB_PORT }}"
            php artisan env:set DB_DATABASE="${{ secrets.DB_NAME }}"
            php artisan env:set DB_USERNAME="${{ secrets.DB_USER }}"
            php artisan env:set DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            php artisan env:set QUEUE_CONNECTION=database
            php artisan migrate --force

